name: xcode build test

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-14','macos-15' ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Xcode version
      run: xcodebuild -version

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: List info (debugging)
      run: |
        echo "Xcode version..."
        xcodebuild -version
        echo "XcodeCLT version..."
        pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
        echo "Xcode SDKs..."
        xcodebuild -sdk -version
        echo "Listing all available simulators..."
        xcrun simctl list

    - name: Create iPhone 15 Pro
      run: |
        xcrun simctl create "iPhone 15 Pro (iOS 18.1)" com.apple.CoreSimulator.SimDeviceType.iPhone-15-Pro com.apple.CoreSimulator.SimRuntime.iOS-18-1

    - name: Build with xcodebuild
      run: xcodebuild -project sim.xcodeproj -scheme sim -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.1'
